shared:
    image: node:6
jobs:
    main:
        steps:
            - print: echo Starting main job!
            - set_meta: |
                foo=$(meta get "foo")
                echo "foo is $foo"
                if [ -z "$foo" ]; then
                    echo "foo is null"
                else
                    echo "foo is not null"
                fi
                meta set "foo" "foobar"
        requires:
            - ~pr
            - ~commit
    second:
        steps:
            - print: echo Starting second job!
            - check_meta: test "foobar" = `meta get "foo"`
            - set_meta: meta set "bar" "barbaz"
        requires: 
            - main
    third:
        steps:
            - print: echo Starting third job!
            - check_meta: test "barbaz" = `meta get "bar"`
        requires:
            - second
    fourth:
        steps:
            - print: echo Starting fourth job!
            - check_meta: |
                test "foobar" = `meta get "foo"`
                test "barbaz" = `meta get "bar"`
        requires:
            - third
    detached:
        steps:
            - print: echo Starting detached job!
            - check_meta: test "barbaz" = `meta get "bar"`        
