shared:
    image: node:6
jobs:
    main:
        steps:
            - print: echo Starting main job!
            - ls: ls -la /opt/sd
            - set: meta set "foo" "foobar"
    second:
        steps:
            - print: echo Starting second job!
            - check_meta: test "foobar" = `meta get "foo"`
            - set_meta: meta set "bar" "barbaz"
    third:
        steps:
            - print: echo Starting third job!
            - check_meta: test "barbaz" = `meta get "bar"`
